/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrientacoesRouteImport } from './routes/orientacoes'
import { Route as PlanosRouteImport } from './routes/planos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientacoesRoute = OrientacoesRouteImport.update({
  id: '/orientacoes',
  path: '/orientacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orientacoes': typeof OrientacoesRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orientacoes': typeof OrientacoesRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orientacoes': typeof OrientacoesRoute
  '/planos': typeof PlanosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orientacoes' | '/planos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orientacoes' | '/planos'
  id: '__root__' | '/' | '/orientacoes' | '/planos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrientacoesRoute: typeof OrientacoesRoute
  PlanosRoute: typeof PlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientacoes': {
      id: '/orientacoes'
      path: '/orientacoes'
      fullPath: '/orientacoes'
      preLoaderRoute: typeof OrientacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrientacoesRoute: OrientacoesRoute,
  PlanosRoute: PlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
